### ISSUE TITLE
consolidate Java-based repositories

### ISSUE THREAD

**Issue by remmeier** [decentralized-identity/did-common-java#1]
currently there are many different repositories:

- verifiable-credentials-java
- did-common-java
- universal-resolver-java 
- http-did-auth-proxy 
- did-auth-relying-party 

some hosted here, other somewhere else. It would be great to see those (some) efforts merged into a single repository with a multi-project setup. This to:

- simplify playing around with the entire tool stack. 
- add documentation spanning all those closely related project (e.g. with asciidoc). 
- Maybe then also to publish the artifacts to jcenter.
- let people star it in one place... :-) 
- aligned versioning to know what works together
- add a build system like travis to verify the components

if there is an interest, I can also help with that.

**Comment by peacekeeper** [comment]
Closing this old issue.. I think the current structure is good, where [jsonld-common-java](https://github.com/decentralized-identity/jsonld-common-java), [did-common-java](https://github.com/decentralized-identity/did-common-java), and others are shared libraries, and [universal-resolver](https://github.com/decentralized-identity/universal-resolver) is a project that uses them.
