### ISSUE TITLE
VC supports?

### ISSUE THREAD

**Issue by Muthurajj** [decentralized-identity/did-common-java#18]
HI @peacekeeper 

I have some point to clear correct me if i am wrong

Create VC with proof using verifiable-credentials-java library
And create DID from the website which you given and add the DID while generating VC
By completing above steps can generate a proper VC that can verify or upload in third party wallet like dock ?? Is any steps missing ??

**Comment by peacekeeper** [comment]
@Muthurajj I'm not very familiar with Dock, but one of the questions is what DID methods they support. E.g. if you issue a VC with a `did:ebsi` or `did:indy` DID, then that will only work in Dock if Dock also supports `did:ebsi` or `did:indy`.

Hope this helps?

**Comment by Muthurajj** [comment]
thanks @peacekeeper
