### ISSUE TITLE
did config uri

### ISSUE THREAD

**Issue by Muthurajj** [decentralized-identity/did-common-java#19]
what is the purpose of this uri linked domain?

**Comment by peacekeeper** [comment]
@Muthurajj do you mean this? https://identity.foundation/.well-known/resources/did-configuration/#LinkedDomains

**Comment by Muthurajj** [comment]
yes @peacekeeper i have read in W3C but i dont understand it and i have list of questions to ask

**Comment by peacekeeper** [comment]
It's basically a way of linking a DID to a domain name. If you have more detailed questions, maybe better to ask them here: https://github.com/decentralized-identity/.well-known/

**Comment by Muthurajj** [comment]
This is question i want to ask 
1.Purpose of use DID-Web & DID-ION
2.SSL & DNS secure access DID
4.Purpose of Expire Date in VC Metadata 
5.what is VC revocation?

**Comment by peacekeeper** [comment]
Sorry, but I don't understand these questions, and I think this isn't the right repository..

**Comment by Muthurajj** [comment]
@peacekeeper do you know about Verifiable credential revocation ?
 and purpose of Expire date in Verifiable credentials?

**Comment by peacekeeper** [comment]
@Muthurajj See my comment here: https://github.com/w3c/did-core/issues/835#issuecomment-1265495361
