### ISSUE TITLE
refine DID object

### ISSUE THREAD

**Issue by remmeier** [decentralized-identity/did-common-java#2]
Some minor things that may help consumers:

- ParserException should become a RuntimeException. Maybe renamed to DidParseException.
- all except didReference should be transient?
- the class itself should be annotated with `@JsonSerialize(using = ToStringSerializer.class)` to be compatible with rest layer.
- equals method is broken ` return this.didReference.equals(obj);` rather than something like `return obj instanceof DID && (this.didReference.equals(((DID) obj).didReference));`

**Comment by mburrows02** [comment]
Additionally, `getId()` seems broken. It returns null if the id is anything other than a URI, but throws a ClassCastException if it is a URI:

    if (! (entry instanceof URI)) return null;
    String id = (String) entry;
    return id;

**Comment by peacekeeper** [comment]
Thanks for the suggestions, feel free to comment or raise more issues if you have further ideas.
