### ISSUE TITLE
adding a `capabilityDelegation` verification method to DID Document actually adds it to `capabilityInvocation`

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/did-common-java#22]
the [`DIDDocument.builder().capabilityDelegationVerificationMethod`](https://github.com/decentralized-identity/did-common-java/blob/main/src/main/java/foundation/identity/did/DIDDocument.java#L143-L145) method actually adds the supplied verification method as a `capabilityInvocation`. 

Is this intentional? if not, PR #21 fixes the issue. feel free to close PR if the way it currently works is intended

**Comment by peacekeeper** [comment]
You're correct, this looks like a bug. Thanks for your contribution!

**Comment by peacekeeper** [comment]
Fixed by https://github.com/decentralized-identity/did-common-java/pull/21
