### ISSUE TITLE
Publish to public maven repository?

### ISSUE THREAD

**Issue by kossmoboleat** [decentralized-identity/did-common-java#4]
This and the other `universal-resolver-java` maven projects look pretty complete. Could they be published to a public repository, so we can reference them in our own projects?

**Comment by kossmoboleat** [comment]
Could publishing to a public maven repo be considered?

**Comment by peacekeeper** [comment]
Hello, it's now possible to get did-common-java from a Maven repository by adding this to your pom.xml (or equivalent in other tools):

```
	<repositories>
		<repository>
			<id>danubetech-maven-public</id>
			<url>https://repo.danubetech.com/repository/maven-public/</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>decentralized-identity</groupId>
			<artifactId>did-common-java</artifactId>
			<version>0.2-SNAPSHOT</version>
		</dependency>
	</dependencies>
```

This should work for both release and snapshot versions.
